---
- name: AS3
  hosts: ip-10-1-1-6.us-west-2.compute.internal
  connection: httpapi
  gather_facts: false

  collections:
    - f5networks.f5_bigip

  vars:
    ansible_host: "{{ inventory_hostname }}"

  tasks:
    - name: Deploy or Update AS3
      bigiq_as3_deploy:
        content: "{{ lookup('file', 'app1-bigiq.json') }}"
        state: absent
        bigip_device: "10.1.1.4"
        tenant: "ansible" 
        
