---
- name: AS3
  hosts: ip-10-1-1-4.us-west-2.compute.internal
  connection: httpapi
  gather_facts: false

  collections:
    - f5networks.f5_bigip

  vars:
    ansible_host: "{{ inventory_hostname }}"

  tasks:
    - name: Deploy or Update AS3
      bigip_as3_deploy:
        content: "{{ lookup('file', 'app1-bigip.json') }}"
        state: absent
        tenant: "ansible"
        
